package com.ecom.cart.filter;

import java.io.IOException;

import org.slf4j.MDC;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Filter that reads correlation ID from request header
 * and puts it into MDC for logging traceability.
 *
 * The correlation ID is generated by API Gateway
 * and propagated across microservices.
 */
@Component
public class LoggingCorrelationFilter extends OncePerRequestFilter {

    private static final String CORRELATION_ID_HEADER = "X-Correlation-ID";

    private static final String TRACE_ID = "traceId";

    @Override
    protected void doFilterInternal(
            HttpServletRequest request,
            HttpServletResponse response,
            FilterChain filterChain)
            throws ServletException, IOException {

        String correlationId =
                request.getHeader(CORRELATION_ID_HEADER);

        // Put correlation ID into MDC
        if (correlationId != null && !correlationId.isBlank()) {
            MDC.put(TRACE_ID, correlationId);
        }

        try {
            filterChain.doFilter(request, response);
        } finally {
            // Prevent memory leaks
            MDC.clear();
        }
    }
}